# SPDX-FileCopyrightText: 2020 Friedrich-Alexander University Erlangen-Nürnberg (FAU)
#
# SPDX-License-Identifier: Apache-2.0

version: "3.7"
services:
  licensee:
    image: docker.pkg.github.com/osrgroup/product-model-toolkit/scanner-licensee:9.13.0
    build: ./licensee/

  scancode:
    image: docker.pkg.github.com/osrgroup/product-model-toolkit/scanner-scancode:3.1.1
    build: ./scancode/
  
  composer:
    image: docker.pkg.github.com/osrgroup/product-model-toolkit/scanner-composer:dummy
    build: ./composer/
  
  file-hasher:
    image: docker.pkg.github.com/osrgroup/product-model-toolkit/file-hasher:latest
    build: ./file-hasher/
