# SPDX-FileCopyrightText: 2020 Friedrich-Alexander University Erlangen-Nürnberg (FAU)
#
# SPDX-License-Identifier: Apache-2.0

name: Go
on: [push, pull_request, workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Restore Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    
    - name: Format Check
      run: diff -u <(echo -n) <(gofmt -d ./)
    
    - name: Test
      run: |
        make test
        make cover

    - name: Build
      run: make build

    - name: Run client
      run: ./pmtclient
      env:
        REMOTEREPO_USER: $GITHUB_ACTOR
        REMOTEREPO_PASS: ${{ secrets.GITHUB_TOKEN }}